# permissions for end users to view persistentpodstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: persistent-pod-state
    app.kubernetes.io/managed-by: kustomize
  name: apps-persistentpodstate-viewer-role
rules:
- apiGroups:
  - apps.clay.io
  resources:
  - persistentpodstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.clay.io
  resources:
  - persistentpodstates/status
  verbs:
  - get
