apiVersion: apps.clay.io/v1alpha1
kind: PersistentPodState
metadata:
  labels:
    app.kubernetes.io/name: persistent-pod-state
    app.kubernetes.io/managed-by: kustomize
  name: persistentpodstate-sample
spec:
  # TODO(user): Add fields here
