//go:build !ignore_autogenerated

/*
Copyright 2025 Clay.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTopologyTerm) DeepCopyInto(out *NodeTopologyTerm) {
	*out = *in
	if in.NodeTopologyKeys != nil {
		in, out := &in.NodeTopologyKeys, &out.NodeTopologyKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTopologyTerm.
func (in *NodeTopologyTerm) DeepCopy() *NodeTopologyTerm {
	if in == nil {
		return nil
	}
	out := new(NodeTopologyTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentPodAnnotation) DeepCopyInto(out *PersistentPodAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentPodAnnotation.
func (in *PersistentPodAnnotation) DeepCopy() *PersistentPodAnnotation {
	if in == nil {
		return nil
	}
	out := new(PersistentPodAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentPodState) DeepCopyInto(out *PersistentPodState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentPodState.
func (in *PersistentPodState) DeepCopy() *PersistentPodState {
	if in == nil {
		return nil
	}
	out := new(PersistentPodState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentPodState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentPodStateList) DeepCopyInto(out *PersistentPodStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PersistentPodState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentPodStateList.
func (in *PersistentPodStateList) DeepCopy() *PersistentPodStateList {
	if in == nil {
		return nil
	}
	out := new(PersistentPodStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersistentPodStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentPodStateSpec) DeepCopyInto(out *PersistentPodStateSpec) {
	*out = *in
	out.TargetReference = in.TargetReference
	if in.PersistentPodAnnotations != nil {
		in, out := &in.PersistentPodAnnotations, &out.PersistentPodAnnotations
		*out = make([]PersistentPodAnnotation, len(*in))
		copy(*out, *in)
	}
	if in.RequiredPersistentTopology != nil {
		in, out := &in.RequiredPersistentTopology, &out.RequiredPersistentTopology
		*out = new(NodeTopologyTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentPodStateSpec.
func (in *PersistentPodStateSpec) DeepCopy() *PersistentPodStateSpec {
	if in == nil {
		return nil
	}
	out := new(PersistentPodStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentPodStateStatus) DeepCopyInto(out *PersistentPodStateStatus) {
	*out = *in
	if in.PodStates != nil {
		in, out := &in.PodStates, &out.PodStates
		*out = make(map[string]PodState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentPodStateStatus.
func (in *PersistentPodStateStatus) DeepCopy() *PersistentPodStateStatus {
	if in == nil {
		return nil
	}
	out := new(PersistentPodStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodState) DeepCopyInto(out *PodState) {
	*out = *in
	if in.NodeTopologyLabels != nil {
		in, out := &in.NodeTopologyLabels, &out.NodeTopologyLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodState.
func (in *PodState) DeepCopy() *PodState {
	if in == nil {
		return nil
	}
	out := new(PodState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}
